name: Python safety check

on:
  push:
    branches:
      - master

env:
  DEP_PATH: src/requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master
        #----------------------------------------------
        #  -----  install & configure poetry  -----
        #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Export requirements to file
        run: |
            poetry export --dev --format=requirements.txt --output=requirements.txt
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master